// Copyright 2025 The entmcp Authors. All rights reserved.
// Use of this source code is governed by an MIT-style
// license that can be found in the LICENSE file.

package entmcp

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"entgo.io/ent/entc/gen"
	"entgo.io/ent/schema/field"
)

// generateMCPHook returns a gen.Hook that generates the entmcp package
// after the standard ent code generation completes.
func generateMCPHook(cfg *Config) gen.Hook {
	return func(next gen.Generator) gen.Generator {
		return gen.GenerateFunc(func(g *gen.Graph) error {
			// Run standard ent generation first.
			if err := next.Generate(g); err != nil {
				return err
			}
			return generateMCPPackage(g, cfg)
		})
	}
}

// generateMCPPackage generates the entmcp subpackage into {target}/entmcp/.
func generateMCPPackage(g *gen.Graph, cfg *Config) error {
	specs, err := buildToolSpecs(g, cfg)
	if err != nil {
		return fmt.Errorf("entmcp: build tool specs: %w", err)
	}
	if len(specs) == 0 {
		return nil
	}

	outDir := filepath.Join(g.Config.Target, "entmcp")
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return fmt.Errorf("entmcp: create output dir: %w", err)
	}

	// Generate the main server file.
	serverSrc, err := genServerFile(g.Config.Package, specs)
	if err != nil {
		return fmt.Errorf("entmcp: gen server file: %w", err)
	}
	if err := writeGoFile(filepath.Join(outDir, "entmcp.go"), serverSrc); err != nil {
		return fmt.Errorf("entmcp: write server file: %w", err)
	}

	// Generate helpers file.
	helpersSrc := genHelpersFile(g.Config.Package)
	if err := writeGoFile(filepath.Join(outDir, "helpers.go"), helpersSrc); err != nil {
		return fmt.Errorf("entmcp: write helpers file: %w", err)
	}

	// Generate per-entity tool files.
	for _, spec := range specs {
		src, err := genEntityToolsFile(g.Config.Package, spec, cfg)
		if err != nil {
			return fmt.Errorf("entmcp: gen tools for %s: %w", spec.TypeName, err)
		}
		filename := filepath.Join(outDir, toSnakeCase(spec.TypeName)+"_tools.go")
		if err := writeGoFile(filename, src); err != nil {
			return fmt.Errorf("entmcp: write tools for %s: %w", spec.TypeName, err)
		}
	}

	// Write JSON manifest if SpecPath is configured.
	if cfg.SpecPath != "" {
		if err := writeSpecManifest(specs, cfg); err != nil {
			return fmt.Errorf("entmcp: write spec manifest: %w", err)
		}
	}

	return nil
}

// writeGoFile formats and writes a Go source file.
func writeGoFile(path, src string) error {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		// Write unformatted file to help with debugging.
		_ = os.WriteFile(path, []byte(src), 0644)
		return fmt.Errorf("format %q: %w\nsource:\n%s", path, err, src)
	}
	return os.WriteFile(path, formatted, 0644)
}

// genServerFile generates the main entmcp.go file.
func genServerFile(entPkg string, specs []ToolSpec) (string, error) {
	var b strings.Builder
	w := func(format string, args ...any) {
		fmt.Fprintf(&b, format, args...)
	}

	w("// Code generated by entmcp. DO NOT EDIT.\n\n")
	w("package entmcp\n\n")
	w("import (\n")
	w("\t\"context\"\n")
	w("\t\"log/slog\"\n\n")
	w("\t\"github.com/modelcontextprotocol/go-sdk/mcp\"\n")
	w("\tent %q\n", entPkg)
	w(")\n\n")

	// ServerOption type.
	w("// ServerOption configures the generated MCP server at runtime.\n")
	w("type ServerOption func(*serverConfig)\n\n")

	w("type serverConfig struct {\n")
	w("\tname        string\n")
	w("\tversion     string\n")
	w("\tlogger      *slog.Logger\n")
	w("\ttoolFilter  func(string) bool\n")
	w("\tcontextFunc func(context.Context) context.Context\n")
	w("}\n\n")

	// ServerOption constructors.
	w("// WithServerInfo sets the server name and version.\n")
	w("func WithServerInfo(name, version string) ServerOption {\n")
	w("\treturn func(c *serverConfig) { c.name = name; c.version = version }\n")
	w("}\n\n")

	w("// WithLogger sets the structured logger for the server.\n")
	w("func WithLogger(l *slog.Logger) ServerOption {\n")
	w("\treturn func(c *serverConfig) { c.logger = l }\n")
	w("}\n\n")

	w("// WithToolFilter sets a function that can disable specific tools by name at runtime.\n")
	w("func WithToolFilter(fn func(name string) bool) ServerOption {\n")
	w("\treturn func(c *serverConfig) { c.toolFilter = fn }\n")
	w("}\n\n")

	w("// WithContextFunc sets a function that enriches the request context (e.g. inject privacy viewer).\n")
	w("func WithContextFunc(fn func(context.Context) context.Context) ServerOption {\n")
	w("\treturn func(c *serverConfig) { c.contextFunc = fn }\n")
	w("}\n\n")

	// NewMCPServer function.
	w("// NewMCPServer creates a new MCP server with all entity tools registered.\n")
	w("// The caller is responsible for choosing a transport and calling server.Run.\n")
	w("func NewMCPServer(client *ent.Client, opts ...ServerOption) *mcp.Server {\n")
	w("\tcfg := &serverConfig{name: \"entmcp\", version: \"v1\"}\n")
	w("\tfor _, opt := range opts {\n\t\topt(cfg)\n\t}\n")
	w("\tif cfg.logger == nil {\n\t\tcfg.logger = slog.Default()\n\t}\n\n")
	w("\tsrv := mcp.NewServer(&mcp.Implementation{Name: cfg.name, Version: cfg.version}, nil)\n\n")

	for _, spec := range specs {
		w("\tregister%sTools(srv, client, cfg)\n", spec.TypeName)
	}

	w("\treturn srv\n")
	w("}\n")

	return b.String(), nil
}

// genHelpersFile generates the helpers.go file with shared utility functions.
func genHelpersFile(entPkg string) string {
	var b strings.Builder
	w := func(format string, args ...any) {
		fmt.Fprintf(&b, format, args...)
	}

	w("// Code generated by entmcp. DO NOT EDIT.\n\n")
	w("package entmcp\n\n")
	w("import (\n")
	w("\t\"encoding/json\"\n")
	w("\t\"fmt\"\n\n")
	// The IsNotFound/IsConstraintError/... helpers live in the user's GENERATED
	// ent package, not in the entgo.io/ent runtime root.
	w("\tent %q\n", entPkg)
	w("\t\"github.com/modelcontextprotocol/go-sdk/mcp\"\n")
	w(")\n\n")

	w("// toolError returns a CallToolResult that represents a tool-level error.\n")
	w("func toolError(msg string) *mcp.CallToolResult {\n")
	w("\treturn &mcp.CallToolResult{\n")
	w("\t\tIsError: true,\n")
	w("\t\tContent: []mcp.Content{&mcp.TextContent{Text: msg}},\n")
	w("\t}\n")
	w("}\n\n")

	w("// toolJSON marshals v and returns it as a text CallToolResult with StructuredContent.\n")
	w("func toolJSON(v any) (*mcp.CallToolResult, error) {\n")
	w("\tb, err := json.Marshal(v)\n")
	w("\tif err != nil {\n")
	w("\t\treturn toolError(\"internal error: marshal result\"), nil\n")
	w("\t}\n")
	w("\ttext := string(b)\n")
	w("\treturn &mcp.CallToolResult{\n")
	w("\t\tContent: []mcp.Content{&mcp.TextContent{Text: text}},\n")
	w("\t}, nil\n")
	w("}\n\n")

	w("// mapEntError maps ent errors to tool-level errors.\n")
	w("func mapEntError(err error, entityType, id string) *mcp.CallToolResult {\n")
	w("\tswitch {\n")
	w("\tcase ent.IsNotFound(err):\n")
	w("\t\tif id != \"\" {\n")
	w("\t\t\treturn toolError(fmt.Sprintf(\"%%s with id %%s not found\", entityType, id))\n")
	w("\t\t}\n")
	w("\t\treturn toolError(fmt.Sprintf(\"%%s not found\", entityType))\n")
	w("\tcase ent.IsConstraintError(err):\n")
	w("\t\treturn toolError(\"constraint violation: \" + sanitizeError(err))\n")
	w("\tcase ent.IsValidationError(err):\n")
	w("\t\treturn toolError(\"validation error: \" + err.Error())\n")
	w("\tcase ent.IsNotSingular(err):\n")
	w("\t\treturn toolError(\"expected one result, got multiple\")\n")
	w("\tdefault:\n")
	w("\t\treturn toolError(\"internal error\")\n")
	w("\t}\n")
	w("}\n\n")

	w("// sanitizeError returns a safe error message without SQL details.\n")
	w("func sanitizeError(err error) string {\n")
	w("\tif err == nil {\n\t\treturn \"\"\n\t}\n")
	w("\tmsg := err.Error()\n")
	w("\t// Strip SQL details — return only the type of constraint violation.\n")
	w("\tif len(msg) > 100 {\n\t\tmsg = msg[:100]\n\t}\n")
	w("\treturn msg\n")
	w("}\n\n")

	w("// boolPtr returns a pointer to the given bool value.\n")
	w("func boolPtr(b bool) *bool { return &b }\n")

	return b.String()
}

// genEntityToolsFile generates the {entity}_tools.go file for one entity.
func genEntityToolsFile(entPkg string, spec ToolSpec, cfg *Config) (string, error) {
	var b bytes.Buffer
	w := func(format string, args ...any) {
		fmt.Fprintf(&b, format, args...)
	}

	w("// Code generated by entmcp. DO NOT EDIT.\n\n")
	w("package entmcp\n\n")

	// Collect required imports.
	imports := []string{
		`"context"`,
		`"encoding/json"`,
		`"fmt"`,
		`"strings"`,
		`"github.com/modelcontextprotocol/go-sdk/mcp"`,
	}
	imports = append(imports, fmt.Sprintf("ent %q", entPkg))
	imports = append(imports, fmt.Sprintf("%q", entPkg+"/"+spec.PackageName))
	imports = append(imports, fmt.Sprintf("%q", entPkg+"/predicate"))

	// Add dialect/sql for ordering support when list op is enabled.
	needsDialectSQL := spec.Ops.Has(OpList)

	// Check if any field uses time.Time.
	needsTime := false
	needsUUID := false
	for _, f := range spec.Fields {
		if f.FieldType == field.TypeTime {
			needsTime = true
		}
		if f.FieldType == field.TypeUUID {
			needsUUID = true
		}
	}
	if spec.IDField.FieldType == field.TypeTime {
		needsTime = true
	}
	if spec.IDField.FieldType == field.TypeUUID {
		needsUUID = true
	}

	if needsTime {
		imports = append(imports, `"time"`)
	}
	if needsUUID {
		imports = append(imports, `"github.com/google/uuid"`)
	}
	if needsDialectSQL {
		imports = append(imports, `"entgo.io/ent/dialect/sql"`)
	}

	sort.Strings(imports)
	w("import (\n")
	for _, imp := range imports {
		w("\t%s\n", imp)
	}
	w(")\n\n")

	// Generate register function.
	genRegisterFunc(&b, spec, cfg)

	// Generate output struct.
	genOutputStruct(&b, spec)

	// Generate list output struct.
	genListOutputStruct(&b, spec)

	// Generate to<Type>Output converter.
	genToOutputFunc(&b, spec)

	// Generate tool handlers.
	if spec.Ops.Has(OpCreate) {
		genCreateHandler(&b, spec)
	}
	if spec.Ops.Has(OpRead) {
		genGetHandler(&b, spec)
	}
	if spec.Ops.Has(OpList) {
		genListHandler(&b, spec, cfg)
	}
	if spec.Ops.Has(OpUpdate) {
		genUpdateHandler(&b, spec)
	}
	if spec.Ops.Has(OpDelete) {
		genDeleteHandler(&b, spec)
	}

	// Suppress unused import warning for pkg if not used in predicates.
	w("\n// Ensure the %s package import is used.\n", spec.PackageName)
	w("var _ = %s.FieldID\n", spec.PackageName)
	w("var _ predicate.%s\n", spec.TypeName)

	// Suppress unused imports.
	w("\n// Suppress unused imports.\n")
	w("var _ = context.Background\n")
	w("var _ = fmt.Sprintf\n")
	w("var _ json.RawMessage\n")
	w("var _ = strings.EqualFold\n")
	if spec.Ops.Has(OpList) {
		w("var _ = sql.OrderDesc\n")
	}

	return b.String(), nil
}

// genRegisterFunc generates the registerXxxTools function.
func genRegisterFunc(b *bytes.Buffer, spec ToolSpec, cfg *Config) {
	w := func(format string, args ...any) {
		fmt.Fprintf(b, format, args...)
	}

	w("// register%sTools registers all MCP tools for the %s entity.\n", spec.TypeName, spec.TypeName)
	w("func register%sTools(srv *mcp.Server, client *ent.Client, cfg *serverConfig) {\n", spec.TypeName)

	if spec.Ops.Has(OpCreate) {
		idTypeStr := jsonSchemaStr(spec.IDField)
		createSchema := genCreateInputSchema(spec)
		w("\t// %s\n", spec.CreateToolName)
		w("\tif cfg.toolFilter == nil || cfg.toolFilter(%q) {\n", spec.CreateToolName)
		w("\t\tsrv.AddTool(&mcp.Tool{\n")
		w("\t\t\tName: %q,\n", spec.CreateToolName)
		w("\t\t\tDescription: \"Create a new %s\",\n", spec.TypeName)
		w("\t\t\tInputSchema: json.RawMessage(`%s`),\n", createSchema)
		w("\t\t\tAnnotations: &mcp.ToolAnnotations{ReadOnlyHint: false},\n")
		w("\t\t}, makeCreate%sHandler(client, cfg))\n", spec.TypeName)
		w("\t}\n")
		_ = idTypeStr
	}

	if spec.Ops.Has(OpRead) {
		idTypeStr := jsonSchemaStr(spec.IDField)
		w("\t// %s\n", spec.GetToolName)
		w("\tif cfg.toolFilter == nil || cfg.toolFilter(%q) {\n", spec.GetToolName)
		w("\t\tsrv.AddTool(&mcp.Tool{\n")
		w("\t\t\tName: %q,\n", spec.GetToolName)
		w("\t\t\tDescription: \"Get a %s by ID\",\n", spec.TypeName)
		w("\t\t\tInputSchema: json.RawMessage(`{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"%s\"}},\"required\":[\"id\"]}`),\n", idTypeStr)
		w("\t\t\tAnnotations: &mcp.ToolAnnotations{ReadOnlyHint: true},\n")
		w("\t\t}, makeGet%sHandler(client, cfg))\n", spec.TypeName)
		w("\t}\n")
	}

	if spec.Ops.Has(OpList) {
		listSchema := genListInputSchema()
		w("\t// %s\n", spec.ListToolName)
		w("\tif cfg.toolFilter == nil || cfg.toolFilter(%q) {\n", spec.ListToolName)
		w("\t\tsrv.AddTool(&mcp.Tool{\n")
		w("\t\t\tName: %q,\n", spec.ListToolName)
		w("\t\t\tDescription: \"List %s with filtering, sorting and pagination\",\n", plural(spec.TypeName))
		w("\t\t\tInputSchema: json.RawMessage(`%s`),\n", listSchema)
		w("\t\t\tAnnotations: &mcp.ToolAnnotations{ReadOnlyHint: true},\n")
		w("\t\t}, makeList%sHandler(client, cfg))\n", spec.TypeName)
		w("\t}\n")
	}

	if spec.Ops.Has(OpUpdate) {
		updateSchema := genUpdateInputSchema(spec)
		w("\t// %s\n", spec.UpdateToolName)
		w("\tif cfg.toolFilter == nil || cfg.toolFilter(%q) {\n", spec.UpdateToolName)
		w("\t\tsrv.AddTool(&mcp.Tool{\n")
		w("\t\t\tName: %q,\n", spec.UpdateToolName)
		w("\t\t\tDescription: \"Update a %s by ID\",\n", spec.TypeName)
		w("\t\t\tInputSchema: json.RawMessage(`%s`),\n", updateSchema)
		w("\t\t\tAnnotations: &mcp.ToolAnnotations{ReadOnlyHint: false, IdempotentHint: true},\n")
		w("\t\t}, makeUpdate%sHandler(client, cfg))\n", spec.TypeName)
		w("\t}\n")
	}

	if spec.Ops.Has(OpDelete) {
		idTypeStr := jsonSchemaStr(spec.IDField)
		w("\t// %s\n", spec.DeleteToolName)
		w("\tif cfg.toolFilter == nil || cfg.toolFilter(%q) {\n", spec.DeleteToolName)
		w("\t\tsrv.AddTool(&mcp.Tool{\n")
		w("\t\t\tName: %q,\n", spec.DeleteToolName)
		w("\t\t\tDescription: \"Delete a %s by ID\",\n", spec.TypeName)
		w("\t\t\tInputSchema: json.RawMessage(`{\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"%s\"}},\"required\":[\"id\"]}`),\n", idTypeStr)
		w("\t\t\tAnnotations: &mcp.ToolAnnotations{ReadOnlyHint: false, IdempotentHint: true, DestructiveHint: boolPtr(true)},\n")
		w("\t\t}, makeDelete%sHandler(client, cfg))\n", spec.TypeName)
		w("\t}\n")
	}

	w("}\n\n")
}

// genOutputStruct generates the XxxOutput struct.
func genOutputStruct(b *bytes.Buffer, spec ToolSpec) {
	w := func(format string, args ...any) {
		fmt.Fprintf(b, format, args...)
	}
	w("// %sOutput is the JSON output shape for %s.\n", spec.TypeName, spec.TypeName)
	w("type %sOutput struct {\n", spec.TypeName)
	w("\tID %s `json:\"id\"`\n", spec.IDField.GoType)
	for _, f := range spec.Fields {
		if f.Sensitive || f.WriteOnly {
			continue
		}
		tag := f.JSONName
		if f.GoTypeNillable {
			w("\t%s %s `json:\"%s,omitempty\"`\n", f.GoName, f.GoType, tag)
		} else {
			w("\t%s %s `json:\"%s\"`\n", f.GoName, f.GoType, tag)
		}
	}
	w("}\n\n")
}

// genListOutputStruct generates the XxxListOutput struct.
func genListOutputStruct(b *bytes.Buffer, spec ToolSpec) {
	w := func(format string, args ...any) {
		fmt.Fprintf(b, format, args...)
	}
	w("// %sListOutput is the list response for %s.\n", spec.TypeName, spec.TypeName)
	w("type %sListOutput struct {\n", spec.TypeName)
	w("\tItems       []*%sOutput `json:\"items\"`\n", spec.TypeName)
	w("\tTotalCount  int          `json:\"total_count\"`\n")
	w("\tPage        int          `json:\"page\"`\n")
	w("\tPageSize    int          `json:\"page_size\"`\n")
	w("\tHasNextPage bool         `json:\"has_next_page\"`\n")
	w("}\n\n")
}

// genToOutputFunc generates the toXxxOutput converter function.
func genToOutputFunc(b *bytes.Buffer, spec ToolSpec) {
	w := func(format string, args ...any) {
		fmt.Fprintf(b, format, args...)
	}
	w("// to%sOutput converts an ent.%s to %sOutput.\n", spec.TypeName, spec.TypeName, spec.TypeName)
	w("func to%sOutput(e *ent.%s) *%sOutput {\n", spec.TypeName, spec.TypeName, spec.TypeName)
	w("\tout := &%sOutput{ID: e.ID}\n", spec.TypeName)
	for _, f := range spec.Fields {
		if f.Sensitive || f.WriteOnly {
			continue
		}
		w("\tout.%s = e.%s\n", f.GoName, f.GoName)
	}
	w("\treturn out\n")
	w("}\n\n")
}

// genCreateHandler generates the makeCreateXxxHandler function.
func genCreateHandler(b *bytes.Buffer, spec ToolSpec) {
	w := func(format string, args ...any) {
		fmt.Fprintf(b, format, args...)
	}
	// Collect create fields.
	var createFields []FieldSpec
	for _, f := range spec.Fields {
		if !f.ReadOnly && !f.Immutable {
			createFields = append(createFields, f)
		}
	}

	w("func makeCreate%sHandler(client *ent.Client, cfg *serverConfig) mcp.ToolHandler {\n", spec.TypeName)
	w("\treturn func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {\n")
	w("\t\tif cfg.contextFunc != nil { ctx = cfg.contextFunc(ctx) }\n")
	w("\t\tvar args map[string]json.RawMessage\n")
	w("\t\tif err := json.Unmarshal(req.Params.Arguments, &args); err != nil {\n")
	w("\t\t\treturn toolError(\"invalid arguments: \" + err.Error()), nil\n")
	w("\t\t}\n")
	w("\t\tbuilder := client.%s.Create()\n", spec.TypeName)
	for _, f := range createFields {
		w("\t\tif v, ok := args[%q]; ok {\n", f.JSONName)
		if f.GoTypeNillable {
			baseType := strings.TrimPrefix(f.GoType, "*")
			w("\t\t\tvar val %s\n", baseType)
			w("\t\t\tif err := json.Unmarshal(v, &val); err != nil {\n")
			w("\t\t\t\treturn toolError(\"invalid field %s: \" + err.Error()), nil\n", f.JSONName)
			w("\t\t\t}\n")
			if f.FieldType == field.TypeBytes || f.FieldType == field.TypeJSON {
				// Bytes/JSON are reference types: ent generates no SetNillable
				// variant, and the setter takes the value directly.
				w("\t\t\tbuilder.Set%s(val)\n", f.GoName)
			} else {
				// Optional scalar: use the pointer-accepting SetNillable setter.
				w("\t\t\tbuilder.SetNillable%s(&val)\n", f.GoName)
			}
		} else {
			w("\t\t\tvar val %s\n", f.GoType)
			w("\t\t\tif err := json.Unmarshal(v, &val); err != nil {\n")
			w("\t\t\t\treturn toolError(\"invalid field %s: \" + err.Error()), nil\n", f.JSONName)
			w("\t\t\t}\n")
			w("\t\t\tbuilder.Set%s(val)\n", f.GoName)
		}
		w("\t\t}\n")
	}
	w("\t\tresult, err := builder.Save(ctx)\n")
	w("\t\tif err != nil {\n")
	w("\t\t\treturn mapEntError(err, %q, \"\"), nil\n", toSnakeCase(spec.TypeName))
	w("\t\t}\n")
	w("\t\treturn toolJSON(to%sOutput(result))\n", spec.TypeName)
	w("\t}\n")
	w("}\n\n")
}

// genGetHandler generates the makeGetXxxHandler function.
func genGetHandler(b *bytes.Buffer, spec ToolSpec) {
	w := func(format string, args ...any) {
		fmt.Fprintf(b, format, args...)
	}
	w("func makeGet%sHandler(client *ent.Client, cfg *serverConfig) mcp.ToolHandler {\n", spec.TypeName)
	w("\treturn func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {\n")
	w("\t\tif cfg.contextFunc != nil { ctx = cfg.contextFunc(ctx) }\n")
	w("\t\tvar args struct {\n")
	w("\t\t\tID %s `json:\"id\"`\n", spec.IDField.GoType)
	w("\t\t}\n")
	w("\t\tif err := json.Unmarshal(req.Params.Arguments, &args); err != nil {\n")
	w("\t\t\treturn toolError(\"invalid arguments: \" + err.Error()), nil\n")
	w("\t\t}\n")
	w("\t\tresult, err := client.%s.Get(ctx, args.ID)\n", spec.TypeName)
	w("\t\tif err != nil {\n")
	w("\t\t\treturn mapEntError(err, %q, fmt.Sprintf(\"%%v\", args.ID)), nil\n", toSnakeCase(spec.TypeName))
	w("\t\t}\n")
	w("\t\treturn toolJSON(to%sOutput(result))\n", spec.TypeName)
	w("\t}\n")
	w("}\n\n")
}

// genListHandler generates the makeListXxxHandler function.
func genListHandler(b *bytes.Buffer, spec ToolSpec, cfg *Config) {
	w := func(format string, args ...any) {
		fmt.Fprintf(b, format, args...)
	}
	w("func makeList%sHandler(client *ent.Client, cfg *serverConfig) mcp.ToolHandler {\n", spec.TypeName)
	w("\treturn func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {\n")
	w("\t\tif cfg.contextFunc != nil { ctx = cfg.contextFunc(ctx) }\n")
	w("\t\tvar args struct {\n")
	w("\t\t\tFilter  map[string]any `json:\"filter,omitempty\"`\n")
	w("\t\t\tOrderBy []struct {\n")
	w("\t\t\t\tField     string `json:\"field\"`\n")
	w("\t\t\t\tDirection string `json:\"direction\"`\n")
	w("\t\t\t} `json:\"order_by,omitempty\"`\n")
	w("\t\t\tPage struct {\n")
	w("\t\t\t\tSize   int `json:\"size,omitempty\"`\n")
	w("\t\t\t\tNumber int `json:\"number,omitempty\"`\n")
	w("\t\t\t} `json:\"page,omitempty\"`\n")
	w("\t\t}\n")
	w("\t\tif err := json.Unmarshal(req.Params.Arguments, &args); err != nil {\n")
	w("\t\t\treturn toolError(\"invalid arguments: \" + err.Error()), nil\n")
	w("\t\t}\n")
	w("\t\tpageSize := args.Page.Size\n")
	w("\t\tif pageSize <= 0 { pageSize = %d }\n", cfg.DefaultPageSize)
	w("\t\tif pageSize > %d { pageSize = %d }\n", cfg.MaxPageSize, cfg.MaxPageSize)
	w("\t\tpageNum := args.Page.Number\n")
	w("\t\tif pageNum < 1 { pageNum = 1 }\n")
	w("\t\toffset := (pageNum - 1) * pageSize\n\n")
	w("\t\tq := client.%s.Query()\n\n", spec.TypeName)
	w("\t\t// Apply filters.\n")
	w("\t\tif len(args.Filter) > 0 {\n")
	w("\t\t\tif preds := build%sPredicates(args.Filter); len(preds) > 0 {\n", spec.TypeName)
	w("\t\t\t\tq = q.Where(preds...)\n")
	w("\t\t\t}\n")
	w("\t\t}\n\n")
	w("\t\t// Apply ordering.\n")
	w("\t\tfor _, o := range args.OrderBy {\n")
	w("\t\t\tif o.Field == \"\" { continue }\n")
	w("\t\t\tisDesc := strings.EqualFold(o.Direction, \"desc\")\n")
	w("\t\t\tswitch o.Field {\n")
	// ID field ordering.
	w("\t\t\tcase \"id\":\n")
	w("\t\t\t\tif isDesc { q = q.Order(%s.ByID(sql.OrderDesc())) } else { q = q.Order(%s.ByID()) }\n", spec.PackageName, spec.PackageName)
	// Per-field ordering.
	for _, f := range spec.Fields {
		if !f.Sortable {
			continue
		}
		w("\t\t\tcase %q:\n", f.JSONName)
		w("\t\t\t\tif isDesc { q = q.Order(%s.By%s(sql.OrderDesc())) } else { q = q.Order(%s.By%s()) }\n",
			spec.PackageName, f.GoName, spec.PackageName, f.GoName)
	}
	w("\t\t\t}\n")
	w("\t\t}\n\n")
	w("\t\ttotal, err := q.Clone().Count(ctx)\n")
	w("\t\tif err != nil {\n")
	w("\t\t\treturn mapEntError(err, %q, \"\"), nil\n", toSnakeCase(spec.TypeName))
	w("\t\t}\n\n")
	w("\t\titems, err := q.Limit(pageSize).Offset(offset).All(ctx)\n")
	w("\t\tif err != nil {\n")
	w("\t\t\treturn mapEntError(err, %q, \"\"), nil\n", toSnakeCase(spec.TypeName))
	w("\t\t}\n\n")
	w("\t\tout := &%sListOutput{\n", spec.TypeName)
	w("\t\t\tItems:       make([]*%sOutput, len(items)),\n", spec.TypeName)
	w("\t\t\tTotalCount:  total,\n")
	w("\t\t\tPage:        pageNum,\n")
	w("\t\t\tPageSize:    pageSize,\n")
	w("\t\t\tHasNextPage: offset+len(items) < total,\n")
	w("\t\t}\n")
	w("\t\tfor i, item := range items {\n")
	w("\t\t\tout.Items[i] = to%sOutput(item)\n", spec.TypeName)
	w("\t\t}\n")
	w("\t\treturn toolJSON(out)\n")
	w("\t}\n")
	w("}\n\n")

	// Generate predicates builder function.
	genPredicatesBuilder(b, spec)
}

// genPredicatesBuilder generates the buildXxxPredicates function.
func genPredicatesBuilder(b *bytes.Buffer, spec ToolSpec) {
	w := func(format string, args ...any) {
		fmt.Fprintf(b, format, args...)
	}
	w("// build%sPredicates converts a filter map to ent predicates.\n", spec.TypeName)
	w("func build%sPredicates(filter map[string]any) []predicate.%s {\n", spec.TypeName, spec.TypeName)
	w("\tvar preds []predicate.%s\n", spec.TypeName)

	// Generate filter handling for each filterable field.
	for _, f := range spec.Fields {
		if len(f.FilterOps) == 0 {
			continue
		}
		w("\t// Filter by %s.\n", f.JSONName)
		w("\tif v, ok := filter[%q]; ok {\n", f.JSONName)
		w("\t\tswitch fv := v.(type) {\n")
		switch f.FieldType {
		case field.TypeString:
			w("\t\tcase string:\n")
			w("\t\t\tpreds = append(preds, %s.%s(fv))\n", spec.PackageName, f.GoName+"EQ")
		case field.TypeInt, field.TypeInt8, field.TypeInt16, field.TypeInt32, field.TypeInt64,
			field.TypeUint, field.TypeUint8, field.TypeUint16, field.TypeUint32, field.TypeUint64:
			// JSON numbers decode to float64; cast to the field's exact Go
			// integer type (e.g. int64) so the predicate signature matches.
			baseType := strings.TrimPrefix(f.GoType, "*")
			w("\t\tcase float64:\n")
			w("\t\t\tpreds = append(preds, %s.%s(%s(fv)))\n", spec.PackageName, f.GoName+"EQ", baseType)
		case field.TypeFloat32, field.TypeFloat64:
			w("\t\tcase float64:\n")
			w("\t\t\tpreds = append(preds, %s.%s(fv))\n", spec.PackageName, f.GoName+"EQ")
		case field.TypeBool:
			w("\t\tcase bool:\n")
			w("\t\t\tpreds = append(preds, %s.%s(fv))\n", spec.PackageName, f.GoName+"EQ")
		case field.TypeEnum:
			w("\t\tcase string:\n")
			// Enum predicates use the generated enum type.
			if f.IsEnum {
				w("\t\t\tpreds = append(preds, %s.%s(%s.%s(fv)))\n", spec.PackageName, f.GoName+"EQ", spec.PackageName, f.GoName)
			} else {
				w("\t\t\tpreds = append(preds, %s.%s(fv))\n", spec.PackageName, f.GoName+"EQ")
			}
		default:
			w("\t\tcase string:\n")
			w("\t\t\t_ = fv // unsupported filter type, ignored\n")
		}
		w("\t\tdefault:\n")
		w("\t\t\t_ = fv\n")
		w("\t\t}\n")
		w("\t}\n")
	}

	w("\treturn preds\n")
	w("}\n\n")
}

// genUpdateHandler generates the makeUpdateXxxHandler function.
func genUpdateHandler(b *bytes.Buffer, spec ToolSpec) {
	w := func(format string, args ...any) {
		fmt.Fprintf(b, format, args...)
	}
	// Collect updatable fields (non-ReadOnly, non-Immutable).
	var updateFields []FieldSpec
	for _, f := range spec.Fields {
		if !f.ReadOnly && !f.Immutable {
			updateFields = append(updateFields, f)
		}
	}

	w("func makeUpdate%sHandler(client *ent.Client, cfg *serverConfig) mcp.ToolHandler {\n", spec.TypeName)
	w("\treturn func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {\n")
	w("\t\tif cfg.contextFunc != nil { ctx = cfg.contextFunc(ctx) }\n")
	w("\t\tvar args map[string]json.RawMessage\n")
	w("\t\tif err := json.Unmarshal(req.Params.Arguments, &args); err != nil {\n")
	w("\t\t\treturn toolError(\"invalid arguments: \" + err.Error()), nil\n")
	w("\t\t}\n")
	w("\t\tidRaw, ok := args[\"id\"]\n")
	w("\t\tif !ok {\n")
	w("\t\t\treturn toolError(\"missing required field: id\"), nil\n")
	w("\t\t}\n")
	w("\t\tvar id %s\n", spec.IDField.GoType)
	w("\t\tif err := json.Unmarshal(idRaw, &id); err != nil {\n")
	w("\t\t\treturn toolError(\"invalid id: \" + err.Error()), nil\n")
	w("\t\t}\n")
	w("\t\tbuilder := client.%s.UpdateOneID(id)\n", spec.TypeName)
	for _, f := range updateFields {
		w("\t\tif v, ok := args[%q]; ok {\n", f.JSONName)
		if f.GoTypeNillable {
			baseType := strings.TrimPrefix(f.GoType, "*")
			w("\t\t\tvar val %s\n", baseType)
			w("\t\t\tif err := json.Unmarshal(v, &val); err != nil {\n")
			w("\t\t\t\treturn toolError(\"invalid field %s: \" + err.Error()), nil\n", f.JSONName)
			w("\t\t\t}\n")
			if f.FieldType == field.TypeBytes || f.FieldType == field.TypeJSON {
				// Bytes/JSON are reference types: ent generates no SetNillable
				// variant, and the setter takes the value directly.
				w("\t\t\tbuilder.Set%s(val)\n", f.GoName)
			} else {
				// Optional scalar: use the pointer-accepting SetNillable setter.
				w("\t\t\tbuilder.SetNillable%s(&val)\n", f.GoName)
			}
		} else {
			w("\t\t\tvar val %s\n", f.GoType)
			w("\t\t\tif err := json.Unmarshal(v, &val); err != nil {\n")
			w("\t\t\t\treturn toolError(\"invalid field %s: \" + err.Error()), nil\n", f.JSONName)
			w("\t\t\t}\n")
			w("\t\t\tbuilder.Set%s(val)\n", f.GoName)
		}
		w("\t\t}\n")
	}
	w("\t\tresult, err := builder.Save(ctx)\n")
	w("\t\tif err != nil {\n")
	w("\t\t\treturn mapEntError(err, %q, fmt.Sprintf(\"%%v\", id)), nil\n", toSnakeCase(spec.TypeName))
	w("\t\t}\n")
	w("\t\treturn toolJSON(to%sOutput(result))\n", spec.TypeName)
	w("\t}\n")
	w("}\n\n")
}

// genDeleteHandler generates the makeDeleteXxxHandler function.
func genDeleteHandler(b *bytes.Buffer, spec ToolSpec) {
	w := func(format string, args ...any) {
		fmt.Fprintf(b, format, args...)
	}
	w("func makeDelete%sHandler(client *ent.Client, cfg *serverConfig) mcp.ToolHandler {\n", spec.TypeName)
	w("\treturn func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {\n")
	w("\t\tif cfg.contextFunc != nil { ctx = cfg.contextFunc(ctx) }\n")
	w("\t\tvar args struct {\n")
	w("\t\t\tID %s `json:\"id\"`\n", spec.IDField.GoType)
	w("\t\t}\n")
	w("\t\tif err := json.Unmarshal(req.Params.Arguments, &args); err != nil {\n")
	w("\t\t\treturn toolError(\"invalid arguments: \" + err.Error()), nil\n")
	w("\t\t}\n")
	w("\t\tif err := client.%s.DeleteOneID(args.ID).Exec(ctx); err != nil {\n", spec.TypeName)
	w("\t\t\treturn mapEntError(err, %q, fmt.Sprintf(\"%%v\", args.ID)), nil\n", toSnakeCase(spec.TypeName))
	w("\t\t}\n")
	w("\t\treturn toolJSON(map[string]any{\"deleted\": true, \"id\": args.ID})\n")
	w("\t}\n")
	w("}\n\n")
}

// jsonSchemaStr returns the JSON Schema "type" string for a field's ID.
func jsonSchemaStr(f FieldSpec) string {
	if f.Schema != nil {
		return f.Schema.Type
	}
	return "string"
}

// genCreateInputSchema generates the JSON Schema for create input.
func genCreateInputSchema(spec ToolSpec) string {
	props := make(map[string]*JSONSchema)
	var required []string
	for _, f := range spec.Fields {
		if f.ReadOnly || f.Immutable {
			continue
		}
		props[f.JSONName] = f.Schema
		if f.Required {
			required = append(required, f.JSONName)
		}
	}
	sort.Strings(required)
	schema := &JSONSchema{
		Type:       "object",
		Properties: props,
		Required:   required,
	}
	b, _ := json.Marshal(schema)
	return string(b)
}

// genUpdateInputSchema generates the JSON Schema for update input.
func genUpdateInputSchema(spec ToolSpec) string {
	props := map[string]*JSONSchema{
		"id": spec.IDField.Schema,
	}
	for _, f := range spec.Fields {
		if f.ReadOnly || f.Immutable {
			continue
		}
		props[f.JSONName] = f.Schema
	}
	schema := &JSONSchema{
		Type:       "object",
		Properties: props,
		Required:   []string{"id"},
	}
	b, _ := json.Marshal(schema)
	return string(b)
}

// genListInputSchema generates the JSON Schema for list input.
func genListInputSchema() string {
	schema := &JSONSchema{
		Type: "object",
		Properties: map[string]*JSONSchema{
			"filter": {Type: "object", Description: "Key-value filter pairs"},
			"order_by": {
				Type: "array",
				Items: &JSONSchema{
					Type: "object",
					Properties: map[string]*JSONSchema{
						"field":     {Type: "string"},
						"direction": {Type: "string", Enum: []string{"asc", "desc"}},
					},
				},
			},
			"page": {
				Type: "object",
				Properties: map[string]*JSONSchema{
					"size":   {Type: "integer", Description: "Number of items per page"},
					"number": {Type: "integer", Description: "Page number (1-based)"},
				},
			},
		},
	}
	b, _ := json.Marshal(schema)
	return string(b)
}

// ToolManifest is the JSON manifest written when SpecPath is configured.
type ToolManifest struct {
	Tools []ToolManifestEntry `json:"tools"`
}

// ToolManifestEntry describes one tool in the manifest.
type ToolManifestEntry struct {
	Name        string `json:"name"`
	Description string `json:"description,omitempty"`
}

// writeSpecManifest writes a JSON manifest of all generated tools.
func writeSpecManifest(specs []ToolSpec, cfg *Config) error {
	manifest := ToolManifest{}
	for _, spec := range specs {
		manifest.Tools = append(manifest.Tools, toolManifestEntries(spec)...)
	}
	b, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return err
	}
	dir := filepath.Dir(cfg.SpecPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	return os.WriteFile(cfg.SpecPath, b, 0644)
}

func toolManifestEntries(spec ToolSpec) []ToolManifestEntry {
	var entries []ToolManifestEntry
	if spec.Ops.Has(OpCreate) {
		entries = append(entries, ToolManifestEntry{Name: spec.CreateToolName, Description: "Create a new " + spec.TypeName})
	}
	if spec.Ops.Has(OpRead) {
		entries = append(entries, ToolManifestEntry{Name: spec.GetToolName, Description: "Get a " + spec.TypeName + " by ID"})
	}
	if spec.Ops.Has(OpList) {
		entries = append(entries, ToolManifestEntry{Name: spec.ListToolName, Description: "List " + plural(spec.TypeName) + " with filtering, sorting and pagination"})
	}
	if spec.Ops.Has(OpUpdate) {
		entries = append(entries, ToolManifestEntry{Name: spec.UpdateToolName, Description: "Update a " + spec.TypeName + " by ID"})
	}
	if spec.Ops.Has(OpDelete) {
		entries = append(entries, ToolManifestEntry{Name: spec.DeleteToolName, Description: "Delete a " + spec.TypeName + " by ID"})
	}
	return entries
}
