// Code generated by entmcp. DO NOT EDIT.

package entmcp

import (
	"context"
	"log/slog"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	ent "github.com/smintz/entmcp/_examples/kitchensink/ent"
)

// ServerOption configures the generated MCP server at runtime.
type ServerOption func(*serverConfig)

type serverConfig struct {
	name        string
	version     string
	logger      *slog.Logger
	toolFilter  func(string) bool
	contextFunc func(context.Context) context.Context
}

// WithServerInfo sets the server name and version.
func WithServerInfo(name, version string) ServerOption {
	return func(c *serverConfig) { c.name = name; c.version = version }
}

// WithLogger sets the structured logger for the server.
func WithLogger(l *slog.Logger) ServerOption {
	return func(c *serverConfig) { c.logger = l }
}

// WithToolFilter sets a function that can disable specific tools by name at runtime.
func WithToolFilter(fn func(name string) bool) ServerOption {
	return func(c *serverConfig) { c.toolFilter = fn }
}

// WithContextFunc sets a function that enriches the request context (e.g. inject privacy viewer).
func WithContextFunc(fn func(context.Context) context.Context) ServerOption {
	return func(c *serverConfig) { c.contextFunc = fn }
}

// NewMCPServer creates a new MCP server with all entity tools registered.
// The caller is responsible for choosing a transport and calling server.Run.
func NewMCPServer(client *ent.Client, opts ...ServerOption) *mcp.Server {
	cfg := &serverConfig{name: "entmcp", version: "v1"}
	for _, opt := range opts {
		opt(cfg)
	}
	if cfg.logger == nil {
		cfg.logger = slog.Default()
	}

	srv := mcp.NewServer(&mcp.Implementation{Name: cfg.name, Version: cfg.version}, nil)

	registerUserTools(srv, client, cfg)
	return srv
}
