// Code generated by entmcp. DO NOT EDIT.

package entmcp

import (
	"encoding/json"
	"fmt"

	"entgo.io/ent"
	"github.com/modelcontextprotocol/go-sdk/mcp"
)

// toolError returns a CallToolResult that represents a tool-level error.
func toolError(msg string) *mcp.CallToolResult {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{&mcp.TextContent{Text: msg}},
	}
}

// toolJSON marshals v and returns it as a text CallToolResult with StructuredContent.
func toolJSON(v any) (*mcp.CallToolResult, error) {
	b, err := json.Marshal(v)
	if err != nil {
		return toolError("internal error: marshal result"), nil
	}
	text := string(b)
	return &mcp.CallToolResult{
		Content: []mcp.Content{&mcp.TextContent{Text: text}},
	}, nil
}

// mapEntError maps ent errors to tool-level errors.
func mapEntError(err error, entityType, id string) *mcp.CallToolResult {
	switch {
	case ent.IsNotFound(err):
		if id != "" {
			return toolError(fmt.Sprintf("%s with id %s not found", entityType, id))
		}
		return toolError(fmt.Sprintf("%s not found", entityType))
	case ent.IsConstraintError(err):
		return toolError("constraint violation: " + sanitizeError(err))
	case ent.IsValidationError(err):
		return toolError("validation error: " + err.Error())
	case ent.IsNotSingular(err):
		return toolError("expected one result, got multiple")
	default:
		return toolError("internal error")
	}
}

// sanitizeError returns a safe error message without SQL details.
func sanitizeError(err error) string {
	if err == nil {
		return ""
	}
	msg := err.Error()
	// Strip SQL details — return only the type of constraint violation.
	if len(msg) > 100 {
		msg = msg[:100]
	}
	return msg
}

// boolPtr returns a pointer to the given bool value.
func boolPtr(b bool) *bool { return &b }
