// Code generated by entmcp. DO NOT EDIT.

package entmcp

import (
	"context"
	"encoding/json"
	"entgo.io/ent/dialect/sql"
	"fmt"
	ent "github.com/smintz/entmcp/_examples/kitchensink/ent"
	"github.com/smintz/entmcp/_examples/kitchensink/ent/predicate"
	"github.com/smintz/entmcp/_examples/kitchensink/ent/user"
	"strings"
	"time"
)

// registerUserTools registers all MCP tools for the User entity.
func registerUserTools(srv *mcp.Server, client *ent.Client, cfg *serverConfig) {
	// create_user
	if cfg.toolFilter == nil || cfg.toolFilter("create_user") {
		srv.AddTool(&mcp.Tool{
			Name:        "create_user",
			Description: "Create a new User",
			InputSchema: json.RawMessage(`{"type":"object","properties":{"active":{"type":"boolean","description":"Whether the user is active"},"age":{"type":"integer","description":"The user's age"},"email":{"type":"string","description":"The user's email address"},"name":{"type":"string","description":"The user's full name"},"password":{"type":"string"}},"required":["email","name"]}`),
			Annotations: &mcp.ToolAnnotations{ReadOnlyHint: false},
		}, makeCreateUserHandler(client, cfg))
	}
	// get_user
	if cfg.toolFilter == nil || cfg.toolFilter("get_user") {
		srv.AddTool(&mcp.Tool{
			Name:        "get_user",
			Description: "Get a User by ID",
			InputSchema: json.RawMessage(`{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}`),
			Annotations: &mcp.ToolAnnotations{ReadOnlyHint: true},
		}, makeGetUserHandler(client, cfg))
	}
	// list_users
	if cfg.toolFilter == nil || cfg.toolFilter("list_users") {
		srv.AddTool(&mcp.Tool{
			Name:        "list_users",
			Description: "List Users with filtering, sorting and pagination",
			InputSchema: json.RawMessage(`{"type":"object","properties":{"filter":{"type":"object","description":"Key-value filter pairs"},"order_by":{"type":"array","items":{"type":"object","properties":{"direction":{"type":"string","enum":["asc","desc"]},"field":{"type":"string"}}}},"page":{"type":"object","properties":{"number":{"type":"integer","description":"Page number (1-based)"},"size":{"type":"integer","description":"Number of items per page"}}}}}`),
			Annotations: &mcp.ToolAnnotations{ReadOnlyHint: true},
		}, makeListUserHandler(client, cfg))
	}
	// update_user
	if cfg.toolFilter == nil || cfg.toolFilter("update_user") {
		srv.AddTool(&mcp.Tool{
			Name:        "update_user",
			Description: "Update a User by ID",
			InputSchema: json.RawMessage(`{"type":"object","properties":{"active":{"type":"boolean","description":"Whether the user is active"},"age":{"type":"integer","description":"The user's age"},"email":{"type":"string","description":"The user's email address"},"id":{"type":"integer"},"name":{"type":"string","description":"The user's full name"},"password":{"type":"string"}},"required":["id"]}`),
			Annotations: &mcp.ToolAnnotations{ReadOnlyHint: false, IdempotentHint: true},
		}, makeUpdateUserHandler(client, cfg))
	}
	// delete_user
	if cfg.toolFilter == nil || cfg.toolFilter("delete_user") {
		srv.AddTool(&mcp.Tool{
			Name:        "delete_user",
			Description: "Delete a User by ID",
			InputSchema: json.RawMessage(`{"type":"object","properties":{"id":{"type":"integer"}},"required":["id"]}`),
			Annotations: &mcp.ToolAnnotations{ReadOnlyHint: false, IdempotentHint: true, DestructiveHint: boolPtr(true)},
		}, makeDeleteUserHandler(client, cfg))
	}
}

// UserOutput is the JSON output shape for User.
type UserOutput struct {
	ID        int       `json:"id"`
	Active    bool      `json:"active"`
	Age       int       `json:"age,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	Name      string    `json:"name"`
}

// UserListOutput is the list response for User.
type UserListOutput struct {
	Items       []*UserOutput `json:"items"`
	TotalCount  int           `json:"total_count"`
	Page        int           `json:"page"`
	PageSize    int           `json:"page_size"`
	HasNextPage bool          `json:"has_next_page"`
}

// toUserOutput converts an ent.User to UserOutput.
func toUserOutput(e *ent.User) *UserOutput {
	out := &UserOutput{ID: e.ID}
	out.Active = e.Active
	out.Age = e.Age
	out.CreatedAt = e.CreatedAt
	out.Email = e.Email
	out.Name = e.Name
	return out
}

func makeCreateUserHandler(client *ent.Client, cfg *serverConfig) mcp.ToolHandler {
	return func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		if cfg.contextFunc != nil {
			ctx = cfg.contextFunc(ctx)
		}
		var args map[string]json.RawMessage
		if err := json.Unmarshal(req.Params.Arguments, &args); err != nil {
			return toolError("invalid arguments: " + err.Error()), nil
		}
		builder := client.User.Create()
		if v, ok := args["active"]; ok {
			var val bool
			if err := json.Unmarshal(v, &val); err != nil {
				return toolError("invalid field active: " + err.Error()), nil
			}
			builder.SetActive(val)
		}
		if v, ok := args["age"]; ok {
			var val int
			if err := json.Unmarshal(v, &val); err != nil {
				return toolError("invalid field age: " + err.Error()), nil
			}
			builder.SetAge(&val)
		}
		if v, ok := args["email"]; ok {
			var val string
			if err := json.Unmarshal(v, &val); err != nil {
				return toolError("invalid field email: " + err.Error()), nil
			}
			builder.SetEmail(val)
		}
		if v, ok := args["name"]; ok {
			var val string
			if err := json.Unmarshal(v, &val); err != nil {
				return toolError("invalid field name: " + err.Error()), nil
			}
			builder.SetName(val)
		}
		if v, ok := args["password"]; ok {
			var val string
			if err := json.Unmarshal(v, &val); err != nil {
				return toolError("invalid field password: " + err.Error()), nil
			}
			builder.SetPassword(&val)
		}
		result, err := builder.Save(ctx)
		if err != nil {
			return mapEntError(err, "user", ""), nil
		}
		return toolJSON(toUserOutput(result))
	}
}

func makeGetUserHandler(client *ent.Client, cfg *serverConfig) mcp.ToolHandler {
	return func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		if cfg.contextFunc != nil {
			ctx = cfg.contextFunc(ctx)
		}
		var args struct {
			ID int `json:"id"`
		}
		if err := json.Unmarshal(req.Params.Arguments, &args); err != nil {
			return toolError("invalid arguments: " + err.Error()), nil
		}
		result, err := client.User.Get(ctx, args.ID)
		if err != nil {
			return mapEntError(err, "user", fmt.Sprintf("%v", args.ID)), nil
		}
		return toolJSON(toUserOutput(result))
	}
}

func makeListUserHandler(client *ent.Client, cfg *serverConfig) mcp.ToolHandler {
	return func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		if cfg.contextFunc != nil {
			ctx = cfg.contextFunc(ctx)
		}
		var args struct {
			Filter  map[string]any `json:"filter,omitempty"`
			OrderBy []struct {
				Field     string `json:"field"`
				Direction string `json:"direction"`
			} `json:"order_by,omitempty"`
			Page struct {
				Size   int `json:"size,omitempty"`
				Number int `json:"number,omitempty"`
			} `json:"page,omitempty"`
		}
		if err := json.Unmarshal(req.Params.Arguments, &args); err != nil {
			return toolError("invalid arguments: " + err.Error()), nil
		}
		pageSize := args.Page.Size
		if pageSize <= 0 {
			pageSize = 25
		}
		if pageSize > 100 {
			pageSize = 100
		}
		pageNum := args.Page.Number
		if pageNum < 1 {
			pageNum = 1
		}
		offset := (pageNum - 1) * pageSize

		q := client.User.Query()

		// Apply filters.
		if len(args.Filter) > 0 {
			if preds := buildUserPredicates(args.Filter); len(preds) > 0 {
				q = q.Where(preds...)
			}
		}

		// Apply ordering.
		for _, o := range args.OrderBy {
			if o.Field == "" {
				continue
			}
			isDesc := strings.EqualFold(o.Direction, "desc")
			switch o.Field {
			case "id":
				if isDesc {
					q = q.Order(user.ByID(sql.OrderDesc()))
				} else {
					q = q.Order(user.ByID())
				}
			case "age":
				if isDesc {
					q = q.Order(user.ByAge(sql.OrderDesc()))
				} else {
					q = q.Order(user.ByAge())
				}
			case "created_at":
				if isDesc {
					q = q.Order(user.ByCreatedAt(sql.OrderDesc()))
				} else {
					q = q.Order(user.ByCreatedAt())
				}
			case "email":
				if isDesc {
					q = q.Order(user.ByEmail(sql.OrderDesc()))
				} else {
					q = q.Order(user.ByEmail())
				}
			case "name":
				if isDesc {
					q = q.Order(user.ByName(sql.OrderDesc()))
				} else {
					q = q.Order(user.ByName())
				}
			}
		}

		total, err := q.Clone().Count(ctx)
		if err != nil {
			return mapEntError(err, "user", ""), nil
		}

		items, err := q.Limit(pageSize).Offset(offset).All(ctx)
		if err != nil {
			return mapEntError(err, "user", ""), nil
		}

		out := &UserListOutput{
			Items:       make([]*UserOutput, len(items)),
			TotalCount:  total,
			Page:        pageNum,
			PageSize:    pageSize,
			HasNextPage: offset+len(items) < total,
		}
		for i, item := range items {
			out.Items[i] = toUserOutput(item)
		}
		return toolJSON(out)
	}
}

// buildUserPredicates converts a filter map to ent predicates.
func buildUserPredicates(filter map[string]any) []predicate.User {
	var preds []predicate.User
	// Filter by active.
	if v, ok := filter["active"]; ok {
		switch fv := v.(type) {
		case bool:
			preds = append(preds, user.ActiveEQ(fv))
		default:
			_ = fv
		}
	}
	// Filter by age.
	if v, ok := filter["age"]; ok {
		switch fv := v.(type) {
		case float64:
			preds = append(preds, user.AgeEQ(int(fv)))
		default:
			_ = fv
		}
	}
	// Filter by created_at.
	if v, ok := filter["created_at"]; ok {
		switch fv := v.(type) {
		case string:
			_ = fv // unsupported filter type, ignored
		default:
			_ = fv
		}
	}
	// Filter by email.
	if v, ok := filter["email"]; ok {
		switch fv := v.(type) {
		case string:
			preds = append(preds, user.EmailEQ(fv))
		default:
			_ = fv
		}
	}
	// Filter by name.
	if v, ok := filter["name"]; ok {
		switch fv := v.(type) {
		case string:
			preds = append(preds, user.NameEQ(fv))
		default:
			_ = fv
		}
	}
	return preds
}

func makeUpdateUserHandler(client *ent.Client, cfg *serverConfig) mcp.ToolHandler {
	return func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		if cfg.contextFunc != nil {
			ctx = cfg.contextFunc(ctx)
		}
		var args map[string]json.RawMessage
		if err := json.Unmarshal(req.Params.Arguments, &args); err != nil {
			return toolError("invalid arguments: " + err.Error()), nil
		}
		idRaw, ok := args["id"]
		if !ok {
			return toolError("missing required field: id"), nil
		}
		var id int
		if err := json.Unmarshal(idRaw, &id); err != nil {
			return toolError("invalid id: " + err.Error()), nil
		}
		builder := client.User.UpdateOneID(id)
		if v, ok := args["active"]; ok {
			var val bool
			if err := json.Unmarshal(v, &val); err != nil {
				return toolError("invalid field active: " + err.Error()), nil
			}
			builder.SetActive(val)
		}
		if v, ok := args["age"]; ok {
			var val int
			if err := json.Unmarshal(v, &val); err != nil {
				return toolError("invalid field age: " + err.Error()), nil
			}
			builder.SetAge(&val)
		}
		if v, ok := args["email"]; ok {
			var val string
			if err := json.Unmarshal(v, &val); err != nil {
				return toolError("invalid field email: " + err.Error()), nil
			}
			builder.SetEmail(val)
		}
		if v, ok := args["name"]; ok {
			var val string
			if err := json.Unmarshal(v, &val); err != nil {
				return toolError("invalid field name: " + err.Error()), nil
			}
			builder.SetName(val)
		}
		if v, ok := args["password"]; ok {
			var val string
			if err := json.Unmarshal(v, &val); err != nil {
				return toolError("invalid field password: " + err.Error()), nil
			}
			builder.SetPassword(&val)
		}
		result, err := builder.Save(ctx)
		if err != nil {
			return mapEntError(err, "user", fmt.Sprintf("%v", id)), nil
		}
		return toolJSON(toUserOutput(result))
	}
}

func makeDeleteUserHandler(client *ent.Client, cfg *serverConfig) mcp.ToolHandler {
	return func(ctx context.Context, req *mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		if cfg.contextFunc != nil {
			ctx = cfg.contextFunc(ctx)
		}
		var args struct {
			ID int `json:"id"`
		}
		if err := json.Unmarshal(req.Params.Arguments, &args); err != nil {
			return toolError("invalid arguments: " + err.Error()), nil
		}
		if err := client.User.DeleteOneID(args.ID).Exec(ctx); err != nil {
			return mapEntError(err, "user", fmt.Sprintf("%v", args.ID)), nil
		}
		return toolJSON(map[string]any{"deleted": true, "id": args.ID})
	}
}

// Ensure the user package import is used.
var _ = user.FieldID
var _ predicate.User

// Suppress unused imports.
var _ = context.Background
var _ = fmt.Sprintf
var _ json.RawMessage
var _ = strings.EqualFold
var _ = sql.OrderDesc
